In [52]:
import numpy as np
from scipy.linalg import orth

def generate_encoder(labels, k):
    rng = np.random.default_rng()
    A = rng.integers(0, 2, size=(labels, k))
    while np.linalg.matrix_rank(A) < k:
        A = rng.integers(0, 2, size=(labels, k))
    return A

# 4 SAMPLES X 4 LABELS
input_m = np.array([
    [1, 1, 0, 1],
    [1, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [1, 0, 1, 1],
    [1, 0, 0, 1],
    [0, 1, 0, 1],
])

# Generar encoder y decoder
k = 3
encoder = generate_encoder(input_m.shape[1], k)
decoder = np.linalg.pinv(encoder)

# Reconstrucción
reconstructed = np.round( (input_m @ encoder) @ decoder )
print( reconstructed )
print( np.sum( (input_m - reconstructed)**2 ) )

[[ 1.  0.  0.  1.]
 [ 1. -0. -0.  1.]
 [ 0.  0.  1. -0.]
 [ 0.  0. -0.  1.]
 [ 1.  0.  1.  1.]
 [ 1. -0. -0.  1.]
 [-0.  1.  0.  1.]]
1.0


In [17]:
print(encoder)
print(np.round(decoder, 5))

[[0 1 1]
 [1 1 1]
 [0 1 1]
 [1 0 1]]
[[-0.5  1.  -0.5 -0. ]
 [-0.   1.   0.  -1. ]
 [ 0.5 -1.   0.5  1. ]]
